const palette = {
  navy: "#1C2B3A",
  navyMid: "#2A3F54",
  navyLight: "#3D5A73",
  sage: "#5C8A6E",
  sageMid: "#7AAF8E",
  sageLight: "#A8CEB8",
  cream: "#F5F1EB",
  creamMid: "#EDE8E0",
  creamDark: "#D9D2C5",
  sand: "#C4B99A",
  amber: "#D4956A",
  amberLight: "#E8B890",
  rose: "#C47A7A",
  roseLight: "#D9A0A0",
  charcoal: "#2C2C2E",
  midGray: "#636366",
  lightGray: "#AEAEB2",
  ultraLight: "#F2F2F7",
  white: "#FFFFFF",
  expansion: "#D4956A",
  structuring: "#5C8A6E",
  recovery: "#7A9CC4",
};

export const Colors = {
  light: {
    background: palette.cream,
    surface: palette.white,
    surfaceSecondary: palette.creamMid,
    border: palette.creamDark,
    borderLight: "#EDE8E0",
    text: palette.navy,
    textSecondary: palette.navyLight,
    textTertiary: palette.midGray,
    textMuted: palette.lightGray,
    tint: palette.navy,
    accent: palette.sage,
    accentLight: palette.sageLight,
    amber: palette.amber,
    amberLight: palette.amberLight,
    rose: palette.rose,
    roseLight: palette.roseLight,
    tabIconDefault: palette.lightGray,
    tabIconSelected: palette.navy,
    // Direct palette tokens (for components that need finer-grained access)
    creamMid: palette.creamMid,
    creamDark: palette.creamDark,
    navyLight: palette.navyLight,
    sage: palette.sage,
    sageLight: palette.sageLight,
    sageMid: palette.sageMid,
    // Phase display colors
    expansion: palette.expansion,
    structuring: palette.structuring,
    recovery: palette.recovery,
    phaseExpansion: "#F4E8D8",
    phaseStructuring: "#DCF0E6",
    phaseRecovery: "#DCE8F4",
    cardShadow: "rgba(28, 43, 58, 0.08)",
    overlay: "rgba(28, 43, 58, 0.4)",
  },
};

export default Colors;
